name: Test-Lint-Build-project
run-name: Test-Lint-Build-project
on: push
jobs:
  Test-Lint-Build-project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Modules
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Lint scripts
        run: npm run lint:scripts
      - name: Lint styles
        run: npm run lint:styles
      - name: Build project
        run: npm run build:prod