# Workflow name
name: 'Screenshot-testing'
run-name: 'Screenshot-testing'

# Event for the workflow
on: push

# List of jobs
jobs:
  screenshot-testing:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Publish to Chromatic
        uses: chromaui/action@v1